### ISSUE TITLE
creation of custom system doesn't populate connection secret

### ISSUE THREAD

**Issue by janwillies** [crossplane-contrib/provider-styra#6]
### What happened?
I tried to create a `system` with type `custom`. The system was created correctly at the styra das api, but the connection secret in kubernetes was empty.

I expected to find the api token in there, or the opa conf, so I can register my opa deployment with the styra das system

### How can we reproduce it?
create a custom system like this:
```yaml
apiVersion: styra.crossplane.io/v1alpha1
kind: System
metadata:
  name: custom-system-demo
spec:
  forProvider:
    description: testing custom opa system
    type: custom
  providerConfigRef:
    name: styra-provider
  writeConnectionSecretToRef:
    name: custom-system-demo
    namespace: crossplane-system
```

### What environment did it happen in?
provider-styra version: 7f325a5
